### ISSUE TITLE
Releases vs tags?

### ISSUE THREAD

**Issue by jas4711** [secure-systems-lab/go-securesystemslib#106]
The tags page show all recent tags including 0.9.0, 0.8.0, 0.7.0 etc:

https://github.com/secure-systems-lab/go-securesystemslib/tags

however the release page is missing the latest releases:

https://github.com/secure-systems-lab/go-securesystemslib/releases

Is this intentional, and does it have some meaning about stability or something?  Or just that you aren't really using the release mechanism?   I don't know GitHub release processes well, so this may just be fine but got me a bit confused.

/Simon

**Comment by adityasaky** [comment]
Releases is a github feature we would create out of a tag. It's not really intentional, we've just not created a release in a while because there also hasn't really been much of a changelog to put in a release. Using the latest tag should be good enough, IMO.

**Comment by jas4711** [comment]
Thank you for clarification!  I'm fine with using tags for Debian, but wanted to confirm that you didn't want the releases to be used instead, for some reason.
