### ISSUE TITLE
EnvelopeVerifier.Verify panics if a nil envelope is provided

### ISSUE THREAD

**Issue by nmiyake** [secure-systems-lab/go-securesystemslib#13]
The [current implementation of EnvelopeVerifier.Verify](https://github.com/secure-systems-lab/go-securesystemslib/blob/main/dsse/verify.go#L34) is:

```
func (ev *EnvelopeVerifier) Verify(e *Envelope) ([]AcceptedKey, error) {
	if len(e.Signatures) == 0 {
		return nil, ErrNoSignature
	}
```

If the provided envelope `e` is `nil`, the `e.Signatures` call results in a panic.

The panic is clearly incorrect behavior -- the function should either:
1. Return an error if `e == nil`
2. Return `nil, nil` if `e == nil` (consider a `nil` envelope to be valid/verified by definition)

I would probably lean more towards (1) since requesting that a `nil` envelope be verified is likely a bug in the logic of the caller, but either approach would work as long as it's documented (and would be preferable to the current behavior).

**Comment by adityasaky** [comment]
I think option 1 makes sense. Can you submit a patch adding that check to the function?

**Comment by adityasaky** [comment]
Thank you, @nmiyake!
