### ISSUE TITLE
use string replace instead of regex in cjson for speed-up

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/go-securesystemslib#24]
Using [`strings.ReplaceAll`](https://pkg.go.dev/strings#ReplaceAll) instead of `re.ReplaceAllString` in below function show yield the same result while being faster.

https://github.com/secure-systems-lab/go-securesystemslib/blob/20c79cb5588a34d84d379f4d2ef6ceaa61f5b989/cjson/canonicaljson.go#L20-L23

This issue was initially raised by @jku in https://github.com/secure-systems-lab/securesystemslib/issues/372 and fixed by @PradyumnaKrishna in https://github.com/secure-systems-lab/securesystemslib/pull/410.

**Comment by adityasaky** [comment]
Closed by #25
