### ISSUE TITLE
Question about using DSSE for verifying persisted data.

### ISSUE THREAD

**Issue by kasia-kittel** [secure-systems-lab/go-securesystemslib#29]
Hey
First of all, thanks for your work towards securing supply chains! 
I use Tekton, and I have a case where I need to verify `in-toto` provenance docs created by Tekton Chains that use DSSE signing. 
The docks are stored in DynamoDB. The structure of the document looks more or less like this:
```
{
	Name: taskrun_id_123 
	Object: { 
			// the in-toto document
	}
	Signed: "..."
	Singnature: "..." //DSSE envelope
}
```
My task is to find a provenance document and verify its signature to assure no one tampered with the record in the database.

I want to use the Verify function from your library, but it doesn't seem to work for my use case. In the source code, I see that the verification only looks at the payload in the envelope. What if someone tampered with the actual `in-toto` document stored in the Object field? 

I wonder if this is a valid use case of the DSSE to verify persisted data. Would it be helpful to have a function that examines the original document? Maybe something like this:

```
func (ev*EnvelopeVerifier) Verify(e*Envelope, original []byte) ([]AcceptedKey, error) {
	body, err:=e.DecodeB64Payload()

	// recalculate the PAE for the original message
	paeEnc:=PAE(e.PayloadType, original)
	
	// and validate it against the signature from the envelope	
	sig, err:=b64Decode(e.Sig)
	(...)
	verify(paeEnc, sig)
	(...)
}
```
Curious about your thoughts.

**Comment by adityasaky** [comment]
Hi @kasia-kittel, thanks for opening the issue. I'm a little confused with the DynamoDB schema you've described here. Can you please clarify how the fields map to the different DSSE fields? The [specification](https://github.com/secure-systems-lab/dsse/blob/master/envelope.md) says an envelope has the following fields: `payload`, `payloadType`, and `signatures`. I think the `signatures` bit has a clear mapping with your schema, but does your `Object` map to the `payload`? In that case, what does `Signed` contain?

**Comment by adityasaky** [comment]
Closing this issue, feel free to reopen if your question remains!
