### ISSUE TITLE
Multi-sign support

### ISSUE THREAD

**Issue by houdini91** [secure-systems-lab/go-securesystemslib#4]
@adityasaky 
Hi all.
I was wondering how to add the multi-signature verification and sign scheme.
If its a feature already been worked on?
Ref [https://github.com/secure-systems-lab/dsse/blob/master/protocol.md#multi-signature-verification](https://github.com/secure-systems-lab/dsse/blob/master/protocol.md#multi-signature-verification)

I would like to hear what are your thoughts about it.

I don't come empty handed.
Suggestion something like this (Draft)

```
type MultiVerifier interface {
	Verify(keyID string, data, sig []byte) (crypto.PublicKey, error)
	KeyID() (string, error)
}

type EnvelopeMultiVerifier struct {
	providers []MultiVerifier
	threshold int
}

func (ev *EnvelopeMultiVerifier) Verify(e *Envelope) ([]crypto.PublicKey, error) {
	if len(e.Signatures) == 0 {
		return nil, ErrNoSignature
	}

	// Decode payload (i.e serialized body)
	body, err := b64Decode(e.Payload)
	if err != nil {
		return nil, err
	}
	// Generate PAE(payloadtype, serialized body)
	paeEnc := PAE(e.PayloadType, string(body))

	// If *any* signature is found to be incorrect, it is skipped
	var accepted_keys []crypto.PublicKey
	for _, s := range e.Signatures {
		sig, err := b64Decode(s.Sig)
		if err != nil {
			return nil, err
		}

		// Loop over the providers.
		// If provider and signiture include keyID's but do not match skip.
		// If a provider recognizes the key, we exit
		// the loop and use the result.
		for _, v := range ev.providers {
			keyID, err := v.KeyID()
			if s.KeyID != "" && keyID != "" && err == nil && s.KeyID != keyID {
				continue
			}

			pub, err := v.Verify(s.KeyID, paeEnc, sig)
			if err != nil {
				continue
			}
			accepted_keys = append(accepted_keys, pub)
			break
		}
	}
	if len(accepted_keys) < ev.threshold {
		return accepted_keys, errors.New(fmt.Sprintf("Accepted signitures do not match threshold, Found: %d, Expected %d", len(accepted_keys), ev.threshold))
	}

	return accepted_keys, nil
}

func NewMultiEnvelopeVerifier(threshold int, p ...MultiVerifier) EnvelopeMultiVerifier {
	ev := EnvelopeMultiVerifier{
		providers: p,
		threshold: threshold,
	}
	return ev
}
```
Notes:
- Maybe instead of returning public keys return there keyids (Which means keyids will become none optional - Does not conform with spec),
  On the other hand using KeyID will prevent the need to change the providers type, allowing the same provider to use both the 
  current `EnvelopeVerifier` and `MultiEnvelopeVerifier`, just a thought.
- There is probably TUF code doing similer logic for its multi-signiture support. 
I probably should take a take a look.

Option2: Another option out the top of my head trying to use a `Public()` interface .
```

type MultiVerifier interface {
	Verifier
	KeyID() (string, error)
	Public() crypto.PublicKey
}

type EnvelopeMultiVerifier struct {
	providers []MultiVerifier
	threshold int
}

func (ev *EnvelopeMultiVerifier) Verify(e *Envelope) ([]crypto.PublicKey, error) {
	if len(e.Signatures) == 0 {
		return nil, ErrNoSignature
	}

	// Decode payload (i.e serialized body)
	body, err := b64Decode(e.Payload)
	if err != nil {
		return nil, err
	}
	// Generate PAE(payloadtype, serialized body)
	paeEnc := PAE(e.PayloadType, string(body))

	// If *any* signature is found to be incorrect, it is skipped
	var accepted_keys []crypto.PublicKey
	for _, s := range e.Signatures {
		sig, err := b64Decode(s.Sig)
		if err != nil {
			return nil, err
		}

		// Loop over the providers.
		// If provider and signiture include keyID's but do not match skip.
		// If a provider recognizes the key, we exit
		// the loop and use the result.
		for _, v := range ev.providers {
			fmt.Println(v.Public())
			keyID, err := v.KeyID()
			if s.KeyID != "" && keyID != "" && err == nil && s.KeyID != keyID {
				continue
			}

			err = v.Verify(s.KeyID, paeEnc, sig)
			if err != nil {
				continue
			}
			pub := v.Public()
			accepted_keys = append(accepted_keys, pub)
			break
		}
	}
	if len(accepted_keys) < ev.threshold {
		return accepted_keys, errors.New(fmt.Sprintf("Accepted signitures do not match threshold, Found: %d, Expected %d", len(accepted_keys), ev.threshold))
	}

	return accepted_keys, nil
}

func NewMultiEnvelopeVerifier(threshold int, p ...MultiVerifier) EnvelopeMultiVerifier {
	ev := EnvelopeMultiVerifier{
		providers: p,
		threshold: threshold,
	}
	return ev
}

```

**Comment by adityasaky** [comment]
* I agree with disallowing 0 thresholds until we have a usecase that calls for it.

* Do we want to treat accepted_keys as a set, so that the length isn't artificially padded?

* Also, I may be overthinking this right now, but I want to confirm that we don't run into issues such as https://github.com/in-toto/in-toto/pull/251 where subkeys were counting towards the threshold. I suppose this can be controlled via what the verifier returns, and what is added to accepted_keys.

**Comment by houdini91** [comment]
@adityasaky , @dlorenc 
Hi.
I created a PR for multi sign and a couple of useful changes.
It sometimes easier to me to write code than English,
Basically i created a multi signature interface then unified the single validation flow underneath.
I also wanted to suggest a change in the interfaces that signers/valiator must obay to include the ability to set a KeyID (option) and return a public key for validation to return. 

Hope i am helping more than i am breaking.

**Comment by adityasaky** [comment]
@houdini91 we can close this now, I believe? :)

**Comment by houdini91** [comment]
> @houdini91 we can close this now, I believe? :)

On my end it seems fine to me. 
It up to you if you guys if you think there should be more stake holders involved or tests in accepting these changes.

What do you think the next step (sigstore integration) ?
@adityasaky

**Comment by adityasaky** [comment]
I think it's best to track that in separate threads here / relevant sigstore repos. :)
