### ISSUE TITLE
DSSE serialization mismatch

### ISSUE THREAD

**Issue by msuozzo** [secure-systems-lab/go-securesystemslib#8]
I believe there's a conflict between the DSSE spec and this implementation.

From the [spec](https://github.com/secure-systems-lab/dsse/blob/master/protocol.md#protocol):

<pre>
To sign:

* Serialize the message according to PAYLOAD_TYPE. <strong>Call the result SERIALIZED_BODY</strong>.
* Sign PAE(UTF8(PAYLOAD_TYPE), <strong>SERIALIZED_BODY</strong>). Call the result SIGNATURE.
* Optionally, compute a KEYID.
* Encode and transmit <strong>SERIALIZED_BODY</strong>, PAYLOAD_TYPE, SIGNATURE, and KEYID, preferably using the recommended JSON envelope.
</pre>

From the [implementation](https://github.com/secure-systems-lab/go-securesystemslib/blob/main/dsse/sign.go#L121):

```
	var e = Envelope{
		Payload:     base64.StdEncoding.EncodeToString(body),
		PayloadType: payloadType,
	}
	paeEnc := PAE(payloadType, body)
```

---

I believe a direct translation of the spec would be as follows:

<pre>
	var e = Envelope{
		Payload:     base64.StdEncoding.EncodeToString(body),
		PayloadType: payloadType,
	}
        paeEnc := PAE(payloadType, <strong>base64.StdEncoding.EncodeToString(body)</strong>)
</pre>

**Comment by dlorenc** [comment]
This function treats the payload type as opaque, so it expects an already serialized payload.

> Serialize the message according to PAYLOAD_TYPE. Call the result SERIALIZED_BODY.

I don't see how we could implement type specific serialization without knowing canonical encodings mapped to their types. Maybe we should just document that this requires the input to be serialized?

**Comment by msuozzo** [comment]
Hmm I don't quite understand your response.

My concern is that different data is being signed than is being included in the payload. If serialization can't be assumed, I would think the data being signed would need to be the base64-serialized one included in the payload.

**Comment by MarkLodato** [comment]
The current implementation is correct. There are two serialization steps:

1. Serializing the payload to some byte sequence, called SERIALIZED_BODY in the spec. That is what the current `SignPayload` accepts (`body []byte`).
2. Serializing the envelope to JSON. Since JSON only has unicode strings, you need to convert the `payload` field to base64.

What you're suggesting is passing Base64 to PAE, which is incorrect.

**Comment by msuozzo** [comment]
Oook I think I see the issue. The first step in the spec is meant to be done outside of this library taking into account the specific payload type. These bytes are encoded using base64 in the output (the "Encode and transmit..." portion of the last step) to ensure they're serializable.

Thanks, Dan and Mark!

**Comment by dlorenc** [comment]
> Oook I think I see the issue. The first step in the spec is meant to be done outside of this library taking into account the specific payload type. These bytes are encoded using base64 in the output (the "Encode and transmit..." portion of the last step) to ensure they're serializable.

Correct! That's much more clear than my explanation, sorry about that. I think you could write a library that does the encoding for you, but you would need to know the "right" encodings for various payload types.
